apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: test23453245345345-hpa
  labels:
    app: test23453245345345
    version: 0.0.1
    backstage.io/kubernetes-id: test23453245345345
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: test23453245345345
 minReplicas: 1
 maxReplicas: 4
 targetCPUUtilizationPercentage: 75